FROM node:19.8.1 as build
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:latest as production
ENV NODE_ENV production

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]